apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: anastasia829/netflix:latest
        ports:
        - containerPort: 80
